#pragma once

#include <cmath>
#include <cstddef>
#include <iomanip>
#include <ios>
#include <limits>
#include <locale>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>
#include "runtime/executor.hpp"
#include "runtime/numeric.hpp"

namespace wickqc::codegen {

// Uses the executor's validated lowering and lifetime schedule. The emitted
// translation unit depends only on wickqc_numeric, and supports runtime sizes.
class CPPEmitter {
 public:
  [[nodiscard]] static std::string Render(
      const runtime::NDArrayExecutor& program,
      std::string_view function_name);
};

namespace cpp_emitter_detail {
inline std::string Quote(std::string_view text) {
  std::ostringstream out;
  out << '"';
  for (const unsigned char c : text) {
    if (c >= 32 && c < 127 && c != '"' && c != '\\') {
      out << c;
    } else {
      out << '\\' << std::oct << std::setw(3) << std::setfill('0')
          << static_cast<unsigned>(c);
    }
  }
  out << '"';
  return out.str();
}

inline std::string Number(double value) {
  if (!std::isfinite(value)) {
    throw std::invalid_argument(
        "Cannot emit a nonfinite contraction coefficient");
  }
  std::ostringstream out;
  out.imbue(std::locale::classic());
  out << std::scientific
      << std::setprecision(std::numeric_limits<double>::max_digits10) << value;
  return out.str();
}

inline std::string List(const std::vector<int>& values) {
  std::string result = "{";
  for (std::size_t i = 0; i < values.size(); ++i) {
    result += (i ? "," : "") + std::to_string(values[i]);
  }
  return result + "}";
}

inline std::string Binding(const runtime::TensorBinding& binding) {
  std::string result = "TensorBinding{" + Quote(binding.name) + ",{";
  for (std::size_t i = 0; i < binding.domains.size(); ++i) {
    const auto domain = binding.domains[i];
    result += (i ? "," : "") + std::string("{") +
        std::to_string(domain.orbital_spaces) + "," +
        std::to_string(domain.spins) + "}";
  }
  return result + "}}";
}
} // namespace cpp_emitter_detail

inline std::string CPPEmitter::Render(
    const runtime::NDArrayExecutor& program,
    std::string_view function_name) {
  if (function_name.empty() ||
      function_name.find_first_not_of(
          "abcdefghijklmnopqrstuvwxyz0123456789_") != std::string_view::npos) {
    throw std::invalid_argument(
        "Generated function suffix must contain only lowercase letters, digits, and underscores");
  }
  using Source = runtime::NDArrayExecutor::Source;
  std::ostringstream out;
  out.imbue(std::locale::classic());
  out << "// Generated by WickQC. Do not edit; regenerate with generate_cpp.\n"
         "#include \"backend/ndarray.hpp\"\n"
         "#include \"runtime/numeric.hpp\"\n"
         "#include <complex>\n"
         "#include <exception>\n"
         "#include <stdexcept>\n"
         "#include <string>\n"
         "#include <utility>\n"
         "#include <vector>\n\n"
         "namespace wickqc::generated {\n"
         "using runtime::Dimensions;\nusing runtime::TensorBinding;\n"
         "using runtime::TensorMap;\nusing runtime::NumericKernel;\n"
      << "const NumericKernel& Kernel_" << function_name
      << "();\nnamespace {\n";
  // Bound each compiler optimization unit even for high-rank CC. The runtime
  // schedule and releases are unchanged across these purely lexical chunks.
  static constexpr std::size_t kChunk = 32;
  for (std::size_t a = 0; a < program.assignments_.size(); ++a) {
    if (a % kChunk == 0) {
      out << "template <typename T>\nvoid Part" << a / kChunk
          << "(const TensorMap<T>& inputs, const Dimensions& dimensions, TensorMap<T>& values) {\n"
             "using Array = NDArray<T>;\n";
    }
    const auto& assignment = program.assignments_[a];
    out << "{\nconst auto shape = "
        << cpp_emitter_detail::Binding(assignment.output)
        << ".Shape(dimensions);\nArray value(shape);\n"
        << "try {\n";
    for (const auto& term : assignment.terms) {
      if (term.operands.empty()) {
        out << "value += Array::Full(shape, T("
            << cpp_emitter_detail::Number(term.coefficient) << "));\n";
        continue;
      }
      out << "{\nstd::vector<Array> arrays;\narrays.reserve("
          << term.operands.size() << ");\n";
      for (const auto& operand : term.operands) {
        const auto& binding = operand.binding;
        switch (operand.source) {
          case Source::kInput:
          case Source::kValue:
            out << "arrays.push_back("
                << (operand.source == Source::kInput ? "inputs" : "values")
                << ".at(" << cpp_emitter_detail::Quote(binding.name) << "));\n";
            break;
          case Source::kOnes:
            out << "arrays.push_back(Array::Ones("
                << cpp_emitter_detail::Binding(binding)
                << ".Shape(dimensions)));\n";
            break;
          case Source::kDelta:
            out << "{ Array delta(" << cpp_emitter_detail::Binding(binding)
                << ".Shape(dimensions));\n"
                   "for (decltype(delta.shape().size()) i = 0; i < delta.shape()[0]; ++i) {\n"
                   "delta.At({i,i}) = T{1};\n}\n"
                   "arrays.push_back(std::move(delta)); }\n";
            break;
        }
      }
      out << "const auto contribution = Array::Einsum(std::vector<std::vector<int>>{";
      for (std::size_t i = 0; i < term.indices.size(); ++i) {
        out << (i ? "," : "") << cpp_emitter_detail::List(term.indices[i]);
      }
      out << "}, " << cpp_emitter_detail::List(term.output_indices)
          << ", arrays);\n"
          << "Array::Copy(contribution, value, {}, T("
          << cpp_emitter_detail::Number(term.coefficient) << "), T{1});\n}\n";
    }
    out << "} catch (const std::exception& error) {\nthrow std::runtime_error(std::string("
        << cpp_emitter_detail::Quote(
               "NDArray output '" + assignment.output.name + "': ")
        << ") + error.what());\n}\n"
        << "Array transformed(shape);\n";
    for (const auto& transform : assignment.transforms) {
      out << "Array::Copy(value, transformed, "
          << cpp_emitter_detail::List(transform.axes) << ", T("
          << cpp_emitter_detail::Number(transform.coefficient) << "), T{1});\n";
    }
    out << "values.emplace("
        << cpp_emitter_detail::Quote(assignment.output.name)
        << ", std::move(transformed));\n";
    for (const auto& name : assignment.release) {
      out << "values.erase(" << cpp_emitter_detail::Quote(name) << ");\n";
    }
    out << "}\n";
    if ((a + 1) % kChunk == 0 || a + 1 == program.assignments_.size()) {
      out << "}\n";
    }
  }
  out << "template <typename T>\nTensorMap<T> Evaluate(const TensorMap<T>& inputs, const Dimensions& dimensions) {\n"
      << "for (const auto& binding : Kernel_" << function_name
      << "().Inputs()) {\n"
         "const auto found = inputs.find(binding.name);\n"
         "if (found == inputs.end()) {\n"
         "throw std::invalid_argument(\"Missing input tensor '\" + binding.name + \"'\");\n}\n"
         "if (found->second.shape() != binding.Shape(dimensions)) {\n"
         "throw std::invalid_argument(\"Shape mismatch for input tensor '\" + binding.name + \"'\");\n}\n}\n"
         "TensorMap<T> values;\n";
  for (std::size_t a = 0; a < program.assignments_.size(); a += kChunk) {
    out << "Part" << a / kChunk << "(inputs, dimensions, values);\n";
  }
  out << "return values;\n}\n} // namespace\n"
      << "const NumericKernel& Kernel_" << function_name
      << "() {\nstatic const NumericKernel kKernel{\n{";
  for (const auto* bindings : {&program.inputs_, &program.outputs_}) {
    for (std::size_t i = 0; i < bindings->size(); ++i) {
      out << (i ? ",\n" : "") << cpp_emitter_detail::Binding(bindings->at(i));
    }
    out << (bindings == &program.inputs_ ? "},\n{" : "},\n");
  }
  out << "&Evaluate<double>, &Evaluate<std::complex<double>>};\nreturn kKernel;\n}\n} // namespace wickqc::generated\n";
  return out.str();
}
} // namespace wickqc::codegen
