#include "codegen/cpp_emitter.hpp"
#include "method/nevpt2.hpp"
#include "runtime/executor.hpp"

#include <exception>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>

namespace {
void Write(const std::filesystem::path& path, const std::string& source) {
  const auto temporary = path.string() + ".tmp";
  std::ofstream output(temporary, std::ios::binary);
  output << source;
  output.close();
  if (!output) {
    throw std::runtime_error("Cannot write generated source " + path.string());
  }
  std::filesystem::rename(temporary, path);
}
void Generate(
    const std::filesystem::path& directory,
    const std::string& prefix,
    const std::string& registry_name,
    const std::vector<
        std::pair<std::string, wickqc::equation::ContractionGraph>>& blocks) {
  std::ostringstream declarations, entries;
  for (const auto& [name, graph] : blocks) {
    const auto program =
        wickqc::runtime::NDArrayExecutor::Compile(graph.Simplify());
    Write(
        directory / (prefix + name + ".generated.cpp"),
        wickqc::codegen::CPPEmitter::Render(program, prefix + name));
    declarations << "const runtime::NumericKernel& Kernel_" << prefix << name
                 << "();\n";
    entries << "{\"" << name << "\", &generated::Kernel_" << prefix << name
            << "()},\n";
    std::cout << name << ": " << program.Inputs().size() << " inputs, "
              << program.Outputs().size() << " outputs\n";
  }
  std::ostringstream registry;
  registry << "// Generated by example_generate_nevpt2. Do not edit.\n"
              "#include \"build_time/kernels.hpp\"\n#include <array>\n"
              "namespace wickqc::generated {\n"
           << declarations.str()
           << "} // namespace wickqc::generated\nnamespace wickqc::example {\n"
              "std::span<const NamedKernel> "
           << registry_name
           << "() {\n"
              "static const std::array<NamedKernel, "
           << blocks.size() << "> kKernels{{\n"
           << entries.str()
           << "}};\nreturn kKernels;\n}\n} // namespace wickqc::example\n";
  Write(directory / (prefix + "registry.generated.cpp"), registry.str());
}
} // namespace

int main(int argc, char** argv) {
  try {
    if (argc != 2) {
      throw std::invalid_argument(
          "Usage: example_generate_nevpt2 OUTPUT_DIRECTORY");
    }
    const std::filesystem::path directory(argv[1]);
    std::filesystem::create_directories(directory);
    Generate(
        directory,
        "sc_",
        "SCNEVPT2Kernels",
        wickqc::method::SCNEVPT2Generator().Equations());
    Generate(
        directory,
        "ic_",
        "ICNEVPT2Kernels",
        wickqc::method::ICNEVPT2Generator().Equations());
  } catch (const std::exception& error) {
    std::cerr << error.what() << '\n';
    return 1;
  }
}
