#include "codegen/cpp_emitter.h"
#include "method/ic_nevpt2.h"
#include "runtime/ndarray_executor.h"

#include <exception>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>

namespace {
void Write(const std::filesystem::path& path, const std::string& source) {
  const auto temporary = path.string() + ".tmp";
  std::ofstream output(temporary, std::ios::binary);
  output << source;
  output.close();
  if (!output) {
    throw std::runtime_error("Cannot write generated source " + path.string());
  }
  std::filesystem::rename(temporary, path);
}
} // namespace

int main(int argc, char** argv) {
  try {
    if (argc != 2) {
      throw std::invalid_argument(
          "Usage: example_generate_nevpt2 OUTPUT_DIRECTORY");
    }
    const std::filesystem::path directory(argv[1]);
    std::filesystem::create_directories(directory);
    const auto blocks = wickqc::method::ICNEVPT2Generator().Equations();
    std::ostringstream declarations, entries;
    for (const auto& [name, graph] : blocks) {
      const auto program =
          wickqc::runtime::NDArrayExecutor::Compile(graph.Simplify());
      Write(
          directory / ("ic_" + name + ".generated.cpp"),
          wickqc::codegen::CPPEmitter::Render(program, "ic_" + name));
      declarations << "const runtime::NumericKernel& Kernel_ic_" << name
                   << "();\n";
      entries << "{\"" << name << "\", &generated::Kernel_ic_" << name
              << "()},\n";
      std::cout << name << ": " << program.Inputs().size() << " inputs, "
                << program.Outputs().size() << " outputs\n";
    }
    std::ostringstream registry;
    registry
        << "// Generated by example_generate_nevpt2. Do not edit.\n"
           "#include \"build_time/kernels.h\"\n#include <array>\n"
           "namespace wickqc::generated {\n"
        << declarations.str()
        << "} // namespace wickqc::generated\nnamespace wickqc::example {\n"
           "std::span<const NamedKernel> ICNEVPT2Kernels() {\n"
           "static const std::array<NamedKernel, "
        << blocks.size() << "> kKernels{{\n"
        << entries.str()
        << "}};\nreturn kKernels;\n}\n} // namespace wickqc::example\n";
    Write(directory / "ic_registry.generated.cpp", registry.str());
  } catch (const std::exception& error) {
    std::cerr << error.what() << '\n';
    return 1;
  }
}
