set(BLAS_BACKEND "NATIVE" CACHE STRING "GEMM backend: MKL, OPENBLAS, BLIS, NATIVE, SIMPLE")
set_property(CACHE BLAS_BACKEND PROPERTY STRINGS MKL OPENBLAS BLIS NATIVE SIMPLE)
string(TOUPPER "${BLAS_BACKEND}" BLAS_BACKEND)
set(_wickqc_backends MKL OPENBLAS BLIS NATIVE SIMPLE)
if(NOT BLAS_BACKEND IN_LIST _wickqc_backends)
  message(FATAL_ERROR "Invalid BLAS_BACKEND='${BLAS_BACKEND}'; choose ${_wickqc_backends}")
endif()

add_library(wickqc_ndarray INTERFACE)
target_include_directories(wickqc_ndarray INTERFACE
  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/src>)
target_compile_features(wickqc_ndarray INTERFACE cxx_std_20)
target_compile_definitions(wickqc_ndarray INTERFACE WICKQC_USE_${BLAS_BACKEND})
target_link_libraries(wickqc_ndarray INTERFACE OpenMP::OpenMP_CXX)

if(BLAS_BACKEND STREQUAL "MKL")
  # Avoid implicitly introducing a second OpenMP runtime into an OpenMP app.
  # Applications can explicitly select gnu_thread/intel_thread when appropriate.
  set(MKL_THREADING sequential CACHE STRING "MKL threading layer")
  find_package(MKL CONFIG REQUIRED HINTS "$ENV{MKLROOT}/lib/cmake/mkl")
  target_link_libraries(wickqc_ndarray INTERFACE MKL::MKL)
elseif(BLAS_BACKEND STREQUAL "OPENBLAS")
  set(OPENBLAS_ROOT "$ENV{HOME}/Applications/OpenBLAS/install" CACHE PATH "OpenBLAS prefix")
  find_path(OPENBLAS_INCLUDE_DIR cblas.h HINTS "${OPENBLAS_ROOT}/include" REQUIRED)
  find_library(OPENBLAS_LIBRARY openblas HINTS "${OPENBLAS_ROOT}/lib" "${OPENBLAS_ROOT}/lib64" REQUIRED)
  target_include_directories(wickqc_ndarray SYSTEM INTERFACE "${OPENBLAS_INCLUDE_DIR}")
  target_link_libraries(wickqc_ndarray INTERFACE "${OPENBLAS_LIBRARY}")
elseif(BLAS_BACKEND STREQUAL "BLIS")
  set(BLIS_ROOT "$ENV{HOME}/Applications/blis/install" CACHE PATH "BLIS prefix (with CBLAS enabled)")
  find_path(BLIS_INCLUDE_DIR cblas.h HINTS "${BLIS_ROOT}/include" PATH_SUFFIXES blis REQUIRED)
  find_library(BLIS_LIBRARY blis HINTS "${BLIS_ROOT}/lib" "${BLIS_ROOT}/lib64" REQUIRED)
  target_include_directories(wickqc_ndarray SYSTEM INTERFACE "${BLIS_INCLUDE_DIR}")
  target_link_libraries(wickqc_ndarray INTERFACE "${BLIS_LIBRARY}")
endif()
message(STATUS "WickQC NDArray GEMM backend: ${BLAS_BACKEND}")
