set(EINSUM_BACKEND "NATIVE" CACHE STRING "Einsum backend: TBLIS, BLIS, MKL, OPENBLAS, NATIVE, SIMPLE")
set_property(CACHE EINSUM_BACKEND PROPERTY STRINGS TBLIS BLIS MKL OPENBLAS NATIVE SIMPLE)
string(TOUPPER "${EINSUM_BACKEND}" EINSUM_BACKEND)
set(_wickqc_einsum_backends TBLIS BLIS MKL OPENBLAS NATIVE SIMPLE)
if(NOT EINSUM_BACKEND IN_LIST _wickqc_einsum_backends)
  message(FATAL_ERROR "Invalid EINSUM_BACKEND='${EINSUM_BACKEND}'; choose ${_wickqc_einsum_backends}")
endif()

add_library(wickqc_ndarray INTERFACE)
target_include_directories(wickqc_ndarray INTERFACE
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/src>)
target_compile_features(wickqc_ndarray INTERFACE cxx_std_20)
target_link_libraries(wickqc_ndarray INTERFACE OpenMP::OpenMP_CXX)
target_compile_definitions(wickqc_ndarray INTERFACE WICKQC_USE_${EINSUM_BACKEND})

if(EINSUM_BACKEND STREQUAL "TBLIS")
  # Use the installed package and its transitive dependencies (TCI/MArray).
  # CMAKE_PREFIX_PATH or TBLIS_ROOT can select a non-system installation.
  find_package(TBLIS CONFIG REQUIRED)
  target_link_libraries(wickqc_ndarray INTERFACE TBLIS::tblis)
elseif(EINSUM_BACKEND STREQUAL "MKL")
  set(MKL_THREADING sequential CACHE STRING "MKL threading layer")
  find_package(MKL CONFIG REQUIRED HINTS "$ENV{MKLROOT}/lib/cmake/mkl")
  target_link_libraries(wickqc_ndarray INTERFACE MKL::MKL)
elseif(EINSUM_BACKEND STREQUAL "OPENBLAS")
  set(OPENBLAS_ROOT "$ENV{HOME}/Applications/OpenBLAS/install" CACHE PATH "OpenBLAS prefix")
  find_path(OPENBLAS_INCLUDE_DIR cblas.h HINTS "${OPENBLAS_ROOT}/include" REQUIRED)
  find_library(OPENBLAS_LIBRARY openblas HINTS "${OPENBLAS_ROOT}/lib" "${OPENBLAS_ROOT}/lib64" REQUIRED)
  target_include_directories(wickqc_ndarray SYSTEM INTERFACE "${OPENBLAS_INCLUDE_DIR}")
  target_link_libraries(wickqc_ndarray INTERFACE "${OPENBLAS_LIBRARY}")
elseif(EINSUM_BACKEND STREQUAL "BLIS")
  set(BLIS_ROOT "$ENV{HOME}/Applications/blis/install" CACHE PATH "BLIS prefix (with CBLAS enabled)")
  find_path(BLIS_INCLUDE_DIR cblas.h HINTS "${BLIS_ROOT}/include" PATH_SUFFIXES blis REQUIRED)
  find_library(BLIS_LIBRARY blis HINTS "${BLIS_ROOT}/lib" "${BLIS_ROOT}/lib64" REQUIRED)
  target_include_directories(wickqc_ndarray SYSTEM INTERFACE "${BLIS_INCLUDE_DIR}")
  target_link_libraries(wickqc_ndarray INTERFACE "${BLIS_LIBRARY}")
endif()
message(STATUS "WickQC NDArray einsum backend: ${EINSUM_BACKEND}")
