include(${CMAKE_CURRENT_LIST_DIR}/NumericalDependencies.cmake)
set(LAPACK_BACKEND "MKL" CACHE STRING "LAPACK backend: MKL, OPENBLAS, NETLIB or EIGEN")
set_property(CACHE LAPACK_BACKEND PROPERTY STRINGS MKL OPENBLAS NETLIB EIGEN)
string(TOUPPER "${LAPACK_BACKEND}" LAPACK_BACKEND)
if(NOT LAPACK_BACKEND MATCHES "^(MKL|OPENBLAS|NETLIB|EIGEN)$")
  message(FATAL_ERROR "Invalid LAPACK_BACKEND='${LAPACK_BACKEND}'; choose MKL, OPENBLAS, NETLIB or EIGEN")
endif()

add_library(wickqc_lapack INTERFACE)
target_include_directories(wickqc_lapack INTERFACE $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/src>)
target_compile_features(wickqc_lapack INTERFACE cxx_std_20)
target_compile_definitions(wickqc_lapack INTERFACE WICKQC_LAPACK_${LAPACK_BACKEND})

if(LAPACK_BACKEND STREQUAL "MKL")
  set(MKL_THREADING sequential CACHE STRING "MKL threading layer")
  find_package(MKL CONFIG REQUIRED HINTS "$ENV{MKLROOT}/lib/cmake/mkl")
  target_link_libraries(wickqc_lapack INTERFACE MKL::MKL)
elseif(LAPACK_BACKEND STREQUAL "NETLIB")
  wickqc_link_netlib(wickqc_lapack LAPACKE)
elseif(LAPACK_BACKEND STREQUAL "EIGEN")
  wickqc_link_eigen(wickqc_lapack)
elseif(LAPACK_BACKEND STREQUAL "OPENBLAS")
  set(OPENBLAS_ROOT "$ENV{HOME}/Applications/OpenBLAS/install" CACHE PATH "OpenBLAS prefix")
  find_path(LAPACK_OPENBLAS_INCLUDE_DIR lapacke.h HINTS "${OPENBLAS_ROOT}/include" REQUIRED)
  find_library(LAPACK_OPENBLAS_LIBRARY openblas
    HINTS "${OPENBLAS_ROOT}/lib" "${OPENBLAS_ROOT}/lib64" REQUIRED)
  target_include_directories(wickqc_lapack SYSTEM INTERFACE "${LAPACK_OPENBLAS_INCLUDE_DIR}")
  target_link_libraries(wickqc_lapack INTERFACE "${LAPACK_OPENBLAS_LIBRARY}")
endif()
message(STATUS "WickQC LAPACK backend: ${LAPACK_BACKEND}")
