set(LAPACK_BACKEND "MKL" CACHE STRING "LAPACK backend: MKL or OPENBLAS")
set_property(CACHE LAPACK_BACKEND PROPERTY STRINGS MKL OPENBLAS)
string(TOUPPER "${LAPACK_BACKEND}" LAPACK_BACKEND)
if(NOT LAPACK_BACKEND MATCHES "^(MKL|OPENBLAS)$")
  message(FATAL_ERROR "Invalid LAPACK_BACKEND='${LAPACK_BACKEND}'; choose MKL or OPENBLAS")
endif()

add_library(wickqc_lapack src/backend/lapack.cpp)
target_include_directories(wickqc_lapack PUBLIC $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/src>)
target_compile_features(wickqc_lapack PUBLIC cxx_std_20)
target_compile_definitions(wickqc_lapack PRIVATE WICKQC_LAPACK_${LAPACK_BACKEND})

if(LAPACK_BACKEND STREQUAL "MKL")
  set(MKL_THREADING sequential CACHE STRING "MKL threading layer")
  find_package(MKL CONFIG REQUIRED HINTS "$ENV{MKLROOT}/lib/cmake/mkl")
  target_link_libraries(wickqc_lapack PRIVATE MKL::MKL)
elseif(LAPACK_BACKEND STREQUAL "OPENBLAS")
  set(OPENBLAS_ROOT "$ENV{HOME}/Applications/OpenBLAS/install" CACHE PATH "OpenBLAS prefix")
  find_path(LAPACK_OPENBLAS_INCLUDE_DIR lapacke.h HINTS "${OPENBLAS_ROOT}/include" REQUIRED)
  find_library(LAPACK_OPENBLAS_LIBRARY openblas
    HINTS "${OPENBLAS_ROOT}/lib" "${OPENBLAS_ROOT}/lib64" REQUIRED)
  target_include_directories(wickqc_lapack SYSTEM PRIVATE "${LAPACK_OPENBLAS_INCLUDE_DIR}")
  target_link_libraries(wickqc_lapack PRIVATE "${LAPACK_OPENBLAS_LIBRARY}")
endif()
message(STATUS "WickQC LAPACK backend: ${LAPACK_BACKEND}")
